name: aiforce
channels:
  - fastai
  - conda-forge
  - defaults
dependencies:
  - anaconda-client
  - conda-build
  - jupyter_conda
  - nbdev
  - opencv>=4.1.2
  - pandas
  - piexif
  - pillow
  - pip
  - python=3.7
  - scikit-image
  - shapely
  - pip:
      - tensorflow
      - tflite-support
      - twine
