# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CATEGORY_LABEL_KEY": "dataset.ipynb",
         "IMAGE_SET_FOLDER": "dataset.ipynb",
         "DEFAULT_CATEGORIES_FILE": "dataset.ipynb",
         "DEFAULT_CLASSIFICATION_ANNOTATIONS_FILE": "dataset.ipynb",
         "DEFAULT_SEGMENTATION_ANNOTATIONS_FILE": "dataset.ipynb",
         "DEFAULT_SPLIT": "dataset.ipynb",
         "DATA_SET_FOLDER": "dataset.ipynb",
         "SEMANTIC_MASK_FOLDER": "dataset.ipynb",
         "IMAGE_EXTENSIONS": "dataset.ipynb",
         "FOLDER_FILTER": "dataset.ipynb",
         "IMAGES_TRAIN_VAL_FOLDER": "dataset.ipynb",
         "IMAGES_TEST_FOLDER": "dataset.ipynb",
         "DATA_SET_TRAIN_FOLDER": "dataset.ipynb",
         "DATA_SET_VAL_FOLDER": "dataset.ipynb",
         "DATA_SET_TEST_FOLDER": "dataset.ipynb",
         "IMAGE_SEGMENTATION": "dataset.ipynb",
         "IMAGE_CLASSIFICATION": "dataset.ipynb",
         "NOT_CATEGORIZED": "dataset.ipynb",
         "logger": "dataset.ipynb",
         "read_categories": "dataset.ipynb",
         "DataSet": "dataset.ipynb",
         "ClassificationDataSet": "dataset.ipynb",
         "SegmentationDataSet": "dataset.ipynb",
         "scan_files": "dataset.ipynb",
         "scan_path": "dataset.ipynb",
         "delete_folder": "dataset.ipynb",
         "create_folder": "dataset.ipynb",
         "split_train_val_data": "dataset.ipynb",
         "input_feedback": "dataset.ipynb",
         "configure_logging": "dataset.ipynb",
         "build_data_set": "dataset.ipynb",
         "BUF_SIZE": "tools-check_double_images.ipynb",
         "FILE_FILTER": "tools-check_double_images.ipynb",
         "IMAGE_EXTENSION": "tools-check_double_images.ipynb",
         "DoubleFileChecker": "tools-check_double_images.ipynb",
         "get_file_sha": "tools-check_double_images.ipynb",
         "check_double_entries": "tools-check_double_images.ipynb",
         "remove_entries": "tools-check_double_images.ipynb",
         "scan_folder": "tools-check_double_images.ipynb",
         "pascal_voc_palette": "tools-color_palette.ipynb",
         "ade20k_palette": "tools-color_palette.ipynb",
         "cityscapes_palette": "tools-color_palette.ipynb",
         "mhp_palette_v1": "tools-color_palette.ipynb"}

modules = ["dataset.py",
           "tools/check_double_images.py",
           "tools/color_palette.py"]

doc_url = "https://ai-force.github.io/ML-Core-Docs/"

git_url = "https://github.com/ai-force/ML-Core/tree/master/"

def custom_doc_links(name): return None
