# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/annotation-multi_category_adapter.ipynb (unless otherwise specified).

__all__ = ['DEFAULT_ANNOTATIONS_FILE', 'CSV_FIELDNAMES', 'logger', 'MultiCategoryAdapter']

# Cell

import csv
import argparse
import shutil
import logging
import os
from os.path import join, basename, isfile, dirname
from ..io.core import create_folder
from .core import Annotation, AnnotationAdapter, Region

# Cell

DEFAULT_ANNOTATIONS_FILE = 'annotations.csv'
CSV_FIELDNAMES = ['image_name', 'tags']

# Cell

logger = logging.getLogger(__name__)

# Cell


class MultiCategoryAdapter(AnnotationAdapter):
    """
    Adapter to read and write annotations for multi label classification.
    `args`: the arguments containing the parameters
    """

    def __init__(self, args):
        super().__init__(args)
        self.files_path = args.files_path
        if args.annotations_file is None:
            self.annotations_file = join(dirname(self.files_path.rstrip(os.sep)), DEFAULT_ANNOTATIONS_FILE)
        else:
            self.annotations_file = args.annotations_file

    def read(self):
        """
        Read annotations from a multi classification CSV annotations file.
        return: the annotations as dictionary
        """
        annotations = {}

        logger.info('Read annotations from {}'.format(self.annotations_file))

        with open(self.annotations_file, newline='') as csv_file:
            reader = csv.DictReader(csv_file)

            skipped_annotations = []
            for row in reader:
                file_path = join(self.files_path, row['image_name'])
                if not isfile(file_path):
                    logger.warning("{}: Source file not found, skip annotation.".format(file_path))
                    skipped_annotations.append(file_path)
                    continue

                if file_path not in annotations:
                    annotations[file_path] = Annotation(annotation_id=file_path, file_path=file_path)

                annotation = annotations[file_path]

                tags = row['tags'] if 'tags' in row else []
                for category in tags.split(' '):
                    region = Region(labels=[category])
                    annotation.regions.append(region)

        logger.info('Finished read annotations')
        logger.info('Annotations read: {}'.format(len(annotations)))
        if skipped_annotations:
            logger.info('Annotations skipped: {}'.format(len(skipped_annotations)))
        return annotations

    def write(self, annotations):
        """
        Writes a multi classification CSV annotations file and copy the corresponding source files.
        `annotations`: the annotations to write
        """
        target_folder = create_folder(self.files_path)
        create_folder(dirname(self.annotations_file))
        logger.info('Write annotations to {}'.format(self.annotations_file))
        logger.info('Write file sources to {}'.format(target_folder))

        skipped_annotations = []
        rows = {}
        for annotation in annotations.values():
            target_file_name = basename(annotation.file_path)
            target_file = join(target_folder, target_file_name)

            if not isfile(annotation.file_path):
                logger.warning("{}: Source file not found, skip annotation.".format(annotation.file_path))
                skipped_annotations.append(annotation.file_path)
                continue

            # copy the file
            if target_file_name not in rows:
                rows[target_file_name] = []
            rows[target_file_name].extend(annotation.labels())

            if isfile(target_file):
                logger.warning("{}: Target file already exist, skip annotation.".format(annotation.file_path))
                skipped_annotations.append(annotation.file_path)
                continue
            shutil.copy2(annotation.file_path, target_file)

        with open(self.annotations_file, 'w', newline='') as csv_file:
            writer = csv.DictWriter(csv_file, fieldnames=CSV_FIELDNAMES, delimiter=',', quotechar='"',
                                    quoting=csv.QUOTE_MINIMAL)
            writer.writeheader()
            writer.writerows([dict(zip(CSV_FIELDNAMES, [key, ' '.join(labels)])) for key, labels in rows.items()])

        logger.info('Finished write annotations')
        logger.info('Annotations written: {}'.format(len(annotations) - len(skipped_annotations)))
        if skipped_annotations:
            logger.info('Annotations skipped: {}'.format(len(skipped_annotations)))

    @classmethod
    def argparse(cls, prefix=None):
        """
        Returns the argument parser containing argument definition for command line use.
        `prefix`: a parameter prefix to set, if needed
        return: the argument parser
        """
        parser = argparse.ArgumentParser()
        parser.add_argument(cls.assign_prefix('--files_path', prefix),
                            dest="files_path",
                            help="The path to the folder containing the files.",
                            required=True)
        parser.add_argument(cls.assign_prefix('--annotations_file', prefix),
                            dest="annotations_file",
                            help="The path to the multi classification CSV annotation file.",
                            default=None)
        return parser
