# AUTOGENERATED! DO NOT EDIT! File to edit: image-inference.ipynb (unless otherwise specified).

__all__ = ['setup_learner', 'fix_odd_sides', 'SegmentationInference']

# Cell

import asyncio
import numpy as np
from ..tools import image as image_tools
from functools import partial
from fastai.basic_train import load_learner
from fastai import vision

# Cell


async def setup_learner(path):
    """
    Setup the learner with weights.
    `path`: The path to the folder containing the exported model file.
    """
    try:
        return load_learner(path.parent, path.name)
    except RuntimeError as e:
        if len(e.args) > 0 and 'CPU-only machine' in e.args[0]:
            print(e)
            messages = [
                "This model was trained with an old version of fastai and will not work in a CPU environment.",
                "Please update the fastai library in your training environment and export your model again.",
            ]
            message = "\n\n{}".format("\n\n".join(messages))
            raise RuntimeError(message)
        else:
            raise

# Cell


def fix_odd_sides(img):
    """
    Fix odd image sizes.
    Odd image sizes can not be divided by 2.
    `img`: The image to fix as fastai image.
    return: the image reference.
    """
    if (list(img.size)[0] % 2) != 0:
        img = vision.crop_pad(img, size=(list(img.size)[0] + 1, list(img.size)[1]), padding_mode='reflection')

    if (list(img.size)[1] % 2) != 0:
        img = vision.crop_pad(img, size=(list(img.size)[0], list(img.size)[1] + 1), padding_mode='reflection')

    return img

# Cell


class SegmentationInference:
    def __init__(self, path, max_size=None):
        self.path = path
        self.max_size = max_size
        loop = asyncio.get_event_loop()
        tasks = [asyncio.ensure_future(setup_learner(path))]
        self.learner = loop.run_until_complete(asyncio.gather(*tasks))[0]
        loop.close()

    def destroy(self):
        """
        Remove the current loaded model from memory.
        """
        if self.learner:
            self.learner.destroy()

    def predict(self, image):
        """
        Predicts an image.

        `image`: the image to predict.
        """
        x = vision.open_image(image, after_open=partial(image_tools.limit_to_max_size, max_size=self.max_size))

        x = fix_odd_sides(x)
        seg, labels, probs = self.learner.predict(x)
        mask = np.asarray(vision.image2np(seg.data), dtype=np.uint8)
        return mask, labels, probs
